// app/layout.tsx
import 'tailwindcss/tailwind.css';
import Navbar from './Components/Navbar';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex min-h-screen flex-col bg-[#F5F5F5] w-full mx-auto px-4 md:px-12 py-2 md:py-4">
        <Navbar />
        <main className="flex-grow p-4">
          {children} {/* Affiche le contenu de la page ici */}
        </main>
      </body>
    </html>
  );
}