import 'tailwindcss/tailwind.css';
import Navbar from './components/navbar/navbar';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex min-h-screen flex-col bg-black w-full mx-auto px-4 md:px-12 py-2 md:py-4">
        <Navbar /> {/* La navbar sera visible sur toutes les pages */}
        {children} {/* Contenu de chaque page */}
      </body>
    </html>
  )
}
